# Generated by Django 3.1.7 on 2021-03-15 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.IntegerField()),
                ('user_zerodha_id', models.CharField(max_length=128)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateTimeField()),
                ('option_range', models.IntegerField()),
                ('option_type', models.CharField(max_length=2)),
                ('sell_price', models.FloatField()),
                ('buy_price', models.FloatField()),
                ('trans_profit', models.FloatField()),
                ('user_regid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbservice.registeredusers')),
            ],
        ),
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.IntegerField()),
                ('user_regid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbservice.registeredusers')),
            ],
        ),
    ]
